<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SystemCare</AssemblyName>
    <RootNamespace>SystemCare</RootNamespace>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
</Project>
