name: Git Commit Data

on:
  push:

permissions:
  contents: read

jobs:
  commit-data:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.21.0
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - name: Git Commit Data
        uses: rlespinasse/git-commit-data-action@v1.5.0
